# Generated by Django 3.1.2 on 2020-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatars/avatar.jpeg', upload_to='user_avatars/%Y/%m/%d'),
        ),
    ]
